### ISSUE TITLE
VM not reported as "started" even after long time

### ISSUE THREAD

**Issue by frisso** [netgroup-polito/CrownLabs#237] opened 2020-04-30 13:47 UTC
The VM is listed in the "starting" state (orange hourglass) forever, without recognizing that the VM is actually ready and the user can connect to it.
Bur reported mostly on Firefox and Safari; some sporadic case in which this bug is also present on Chrome.

Temporary solution: log out of Crownlabs, re-enter again, and usually the VM has become green.

**Comment by GabriFila** [comment] 2020-04-30 21:10
Do you believe it could be related to #126?

**Comment by frisso** [comment] 2020-10-07 20:48
@giorio94 I think we can close this, isn't it? Thanks!

**Comment by GabriFila** [comment] 2020-10-07 21:14
Sadly no, at the moment on Firefox the watcher still breaks, so VMs don't show up if they were active before coming to the page.
We need to understand why the watcher behaves like this, but for the moment a possible patch would be to manually ask the instance status when it fails (if we can catch it)

**Comment by giorio94** [comment] 2020-10-08 07:23
As confirmed also by @GabriFila, this bug is still present in Firefox since the watcher sometimes breaks and thus no updates are received by the dashboard.

Yet, closing as a duplicate of #126, which already tracks this issue

**Closed by giorio94** 2020-10-08 07:23 UTC
Labels: bug, sig-api, sig-ui
